name: format-python

on:
  pull_request:
    branches: [main]

jobs:
  format-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install requirements
        run: |
          python -m pip install -U pip
          pip install -U black==22.1.0 blackdoc==0.3.4 hacking==4.1.0 isort==5.10.1 mypy==0.931

      - name: Run black
        run: black src/ --check --diff

      - name: Run blackdoc
        run: blackdoc src/ --check --diff

      - name: Run flake8
        run: flake8 src/

      - name: Run isort
        run: isort src/ --check --diff

      - name: Run mypy
        run: mypy src/
