name: format-yaml

on:
  pull_request:
    branches: [main]

jobs:
  format-yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install requirements
        run: |
          python -m pip install -U pip
          pip install -U yamllint==1.26.3

      - name: Run yamllint
        run: yamllint .
